export const PRIVACY_POLICY = `
BIGKAS PRIVACY POLICY
Effective Date: April 12, 2026

1. INFORMATION COLLECTION
Bigkas collects information you provide directly, such as when you create an account, and information generated by your use of the application, including:
- Voice recordings for speech analysis.
- Speech metrics and performance data.
- Basic account information (e.g., username, email).

2. BIOMETRIC DATA RETENTION POLICY
In compliance with data protection standards:
- All voice recordings and related biometric patterns are stored securely.
- We implement a strict 14-day biometric data retention policy.
- Voice data is automatically and permanently deleted from our active storage 14 days after it is processed.

3. USE OF INFORMATION
We use the information we collect to:
- Provide speech coaching and analysis.
- Track and display your progress in the Skyward Journey.
- Improve our speech recognition and analysis algorithms.
- Communicate with you about your account.

4. DATA SHARING
Bigkas does not sell your personal data. We do not share your biometric information with third parties for their own marketing or commercial purposes.

5. DATA SECURITY
We use industry-standard encryption and security measures to protect your information.

6. USER RIGHTS
You have the right to:
- Access the personal information we hold about you.
- Request the deletion of your account and associated data at any time.
- Opt-out of non-essential data collection.

7. CONTACT US
If you have questions about this Privacy Policy, please contact our support team.
`;
