/**
 * practiceData.js — System pre-written speeches and randomiser topics.
 * Expanded with over 200+ topics for comprehensive training.
 */

export const SYSTEM_PREWRITTEN_SPEECHES = [
  {
    id: 'sys-1',
    type: 'system-prewritten',
    title: 'Graduation Speech',
    content:
      'To the graduates of today, look at the person sitting next to you. In this moment, you share a common victory, but tomorrow, your paths will diverge into a world that is as beautiful as it is unpredictable. Graduation is not merely a destination; it is the starting line of a marathon that lasts a lifetime. You have spent years mastering theories, passing exams, and navigating the complexities of student life. But as you step outside these walls, you will find that the most important lessons aren\'t found in textbooks.\n\nThe world you are entering values adaptability over rigid knowledge. It values the courage to say "I don\'t know, but I will find out" over the arrogance of pretending to have all the answers. Think of the pioneers who changed the course of history. They weren\'t necessarily the smartest people in the room, but they were the ones most willing to stay in the room when everyone else left. They understood that persistence is the silent engine of genius.\n\nAs you pursue your careers, do not let the fear of making a mistake keep you from making a difference. Your degree is a tool, but your character is the hand that wields it. Be kind to those you meet on your way up, for they are the same people you will meet on your way down. Practice empathy as rigorously as you practice your profession. In a digital age where we can be anything, choose to be human. Congratulations on this milestone. Now, go out there and build a world that is better than the one we gave you. Your journey has only just begun, and the horizon is wider than you can possibly imagine.',
  },
  {
    id: 'sys-2',
    type: 'system-prewritten',
    title: 'Wedding Toast',
    content:
      'We are gathered here today to witness a miracle—not the kind that defies the laws of physics, but the kind that defies the odds of the heart. To see two people find each other in a world of eight billion and say, "You are the one I choose to walk with," is nothing short of extraordinary. Love is often described in movies as a lightning bolt, a sudden and overwhelming force. But those who have been married for decades will tell you that real love isn\'t a lightning bolt; it is a hearth fire. It is something that must be tended, protected from the wind, and fueled with the wood of patience and the kindling of humor.\n\nA successful marriage is not a union of two perfect people, for perfection is a myth that prevents growth. It is the union of two people who are willing to be imperfect together. It is about the small moments—the shared coffee in the morning, the quiet support during a difficult work week, and the ability to laugh at yourselves when things go wrong. It is about being each other\'s safe harbor when the world feels chaotic.\n\nTo the couple: never stop being curious about each other. As the years pass, you will both change. You will grow, your dreams will evolve, and your perspectives will shift. The secret to staying together is to fall in love with the new versions of your partner as they emerge. Support each other’s individual growth as fiercely as you support your shared life. Remember that a "sorry" said early is worth more than an "I told you so" said late. May your home be filled with laughter that echoes, joy that sustains, and a love that grows deeper with every passing sunset. Please join me in raising a glass to a lifetime of shared adventures and unbreakable bonds.',
  },
  {
    id: 'sys-3',
    type: 'system-prewritten',
    title: 'Eulogy',
    content:
      'We come together today with heavy hearts, but also with spirits filled with gratitude. We are here to honor a life that was not measured in years, but in the lives touched, the stories told, and the love shared. When we lose someone we love, the world feels a little quieter, a little colder. But as we reflect on the legacy left behind, we realize that the flame of a good life is never truly extinguished; it simply moves from the physical world into the hearts of those who remain.\n\nWhat truly defines a person? It isn\'t their titles or their bank accounts. It is the way they made people feel. It is the kindness they showed when no one was watching. It is the resilience they displayed during their darkest hours. Our dear friend taught us that the greatest gift you can give someone is your time and your presence. They were a listener, a mentor, and a beacon of hope for so many of us here today. They understood that life is fragile and that every moment is a precious opportunity to create a memory.\n\nThough they are no longer with us in person, their influence is woven into the fabric of our lives. Every time we show courage, every time we choose kindness over anger, and every time we help someone in need, we are honoring their memory. Death ends a life, but it does not end a relationship. The bond we share with them remains. So, as we say our final goodbyes, let us not focus on the void they left behind, but on the light they brought into our world. Let us live our lives with a little more passion and a little more grace, just as they did. Rest well, dear friend. You have run your race, and you have finished strong. We will carry your torch from here.',
  },
  {
    id: 'sys-4',
    type: 'system-prewritten',
    title: 'Keynote Speech',
    content:
      'In this hall of innovation, we often talk about the "Next Big Thing." We talk about algorithms, automation, and the digital frontier. But as we look toward the future, we must remember that technology is merely a mirror of human intent. Innovation isn\'t about the machines we build; it is about the problems we solve and the people we empower. We are living in an era of unprecedented connectivity, yet we face challenges that require more than just technical solutions. They require a rekindling of the human spirit.\n\nThe most transformative innovations in history didn\'t come from a boardroom; they came from a place of deep empathy. They came from someone seeing a struggle and saying, "There must be a better way." As leaders in this industry, our responsibility goes beyond the bottom line. We have a duty to ensure that as our systems get smarter, our societies get fairer. We must bridge the gap between those who have access to the future and those who are being left behind in the past.\n\nDon\'t be afraid of the disruption that technology brings. Disruption is simply the birth pains of progress. But as we disrupt industries, let us not disrupt our ethics. Let us use our tools to amplify voices that have been silenced, to protect the environment that sustains us, and to solve the health crises that plague our communities. The future isn\'t something that happens to us; it is something we create with every line of code and every strategic decision. Let us build a future that our children will be proud to inherit—a future where technology serves humanity, and not the other way around. Let us innovate with purpose, lead with integrity, and never lose sight of the people behind the data.',
  },
  {
    id: 'sys-5',
    type: 'system-prewritten',
    title: 'Award Acceptance Speech',
    content:
      'I stand here tonight deeply humbled and profoundly grateful. Receiving this recognition is an honor I never expected when I first started this journey. But as I look at this award, I don\'t see my own reflection; I see the faces of the dozens of people who helped me get here. No one ever truly succeeds alone. We are all the products of the people who believed in us when we didn\'t believe in ourselves, the mentors who pushed us to be better, and the colleagues who stood by us during the long nights and the difficult setbacks.\n\nTo my family, thank you for being my anchor. Your unconditional support gave me the freedom to take risks and the safety to fail. To my team, this award belongs to you as much as it does to me. Your dedication, your brilliance, and your tireless work ethic are the real reasons we are celebrating tonight. You challenged me, you inspired me, and you made the impossible feel achievable. This journey was never about reaching a podium; it was about the work we did together every single day.\n\nFor those of you who are just starting out, perhaps feeling overwhelmed or overlooked, let this be a reminder that persistence pays off. Success is rarely a straight line; it is a winding path filled with obstacles and detours. The key is to keep moving, to keep learning, and to never lose sight of your "why." Use your platform to lift others up. True success is only meaningful when it is used to create opportunities for someone else. I accept this award not as a final destination, but as an inspiration to keep pushing boundaries and to keep serving this community with everything I have. Thank you for this incredible honor.',
  },
  {
    id: 'sys-6',
    type: 'system-prewritten',
    title: 'Holiday Speech',
    content:
      'As the year draws to a close and the holiday season settles upon us, we find ourselves at a unique crossroads of time. The holidays are more than just a break from our routines or a series of dates on a calendar; they are a universal pause button. They provide us with a rare opportunity to look back at the challenges we have weathered and forward to the possibilities that await. In the rush of gift-giving and event-planning, it is easy to lose sight of the true essence of this season: connection and gratitude. \n\nThink about the traditions that define your holidays. Whether it is a specific meal, a familiar song, or a gathering of distant relatives, these rituals serve as the glue that binds generations together. They remind us that despite the rapid pace of a changing world, some things remain constant—the warmth of a home, the sound of laughter, and the value of shared moments. This season, I challenge you to look beyond the material aspects of the holidays. Instead, focus on being present. The greatest gift you can offer anyone is your undivided attention and a kind word.\n\nLet us also remember those for whom the holidays may be difficult. For many, this time of year highlights absence rather than presence. By reaching out with a simple gesture of inclusion, we can embody the true spirit of the season. As we celebrate, let us carry the spirit of generosity and peace into the coming year. May your holidays be a time of profound rest and joyful reconnection. Let the light of this season stay with you long after the decorations are put away, guiding you toward a year filled with purpose and compassion.',
  },
  {
    id: 'sys-7',
    type: 'system-prewritten',
    title: 'Christmas Speech',
    content:
      'Christmas is a season that speaks to the deepest parts of our humanity. It is a time when we celebrate the birth of hope in the midst of a cold winter. Regardless of your personal beliefs, the message of Christmas is one that resonates across cultures and borders: the idea that even in the darkest of times, light can break through. We see this light in the eyes of children, in the selfless acts of volunteers, and in the resilience of families coming together against all odds. \n\nThis year, as we gather around our Christmas trees and share meals with loved ones, let us reflect on the power of small beginnings. Just as a tiny star once guided travelers through a vast desert, small acts of kindness can guide others through their personal deserts of loneliness or despair. Christmas reminds us that we are part of something larger than ourselves. It is a call to practice "Bayanihan" in our own unique way—to carry the burdens of our neighbors and to celebrate their victories as our own.\n\nAs you unwrap gifts today, remember the gifts that cannot be bought: the gift of forgiveness, the gift of a fresh start, and the gift of hope. Let the joy of this day soften the hard edges of our lives. Let us make a commitment to keep the Christmas spirit alive not just in December, but every day of our lives. By choosing love over hate and understanding over judgment, we make every day a little more like Christmas. I wish you all a Merry Christmas filled with the peace that surpasses all understanding and the joy that comes from truly belonging.',
  },
  {
    id: 'sys-8',
    type: 'system-prewritten',
    title: 'Birthday Speech',
    content:
      'Birthdays are often seen as a time to count years, but today, I want to suggest that we count experiences instead. We are here to celebrate a person who has not just existed for another year, but who has truly lived. Life is a complex tapestry woven from threads of joy, sorrow, risk, and triumph. Each year added to our age represents a chapter of growth that has shaped the person standing before us today. We aren\'t just celebrating a date; we are celebrating the resilience, the wisdom, and the humor that you have cultivated along the way.\n\nTo the birthday celebrant: look back at the versions of yourself from five, ten, or twenty years ago. Think of the obstacles you thought were insurmountable and the dreams you were once too afraid to speak aloud. You have navigated through storms that others never saw, and you have found sunshine in places you never expected. Your journey is unique, and it is beautiful. Today is a reminder that you are a work in progress, and the best chapters are often the ones yet to be written. \n\nAs you step into this new year of life, I hope you continue to be bold. I hope you continue to ask "Why?" and "What if?" with the curiosity of a child. Never let the world dull your spark or convince you that you have seen it all. Surround yourself with people who challenge you and who love you for exactly who you are. May this year be one of unexpected adventures, deep fulfillment, and the kind of happiness that starts from within. Happy Birthday—here is to the life you have lived and the incredible future you are still creating.',
  },
  {
    id: 'sys-9',
    type: 'system-prewritten',
    title: 'Appreciation Speech',
    content:
      'I want to take a few minutes today to talk about something that often goes unsaid but is essential to the health of any community or organization: the power of appreciation. We live in a world that is obsessed with the "next milestone." We are constantly looking at what we haven\'t achieved yet, what we haven\'t finished, or where we have fallen short. In this constant pursuit of "more," we often forget to acknowledge the incredible work and the wonderful people who are making a difference right here and now.\n\nRecognition is not just a polite gesture; it is the fuel of human motivation. When we take the time to say "I see what you did, and it matters," we are validating someone\'s effort and their worth. To those of you I am acknowledging today: your dedication has not gone unnoticed. You have gone above and beyond, not because you were asked to, but because you care. Your attention to detail, your willingness to help others, and your consistent positive attitude have created a ripple effect that benefits all of us. You make this place better simply by being in it.\n\nLet this be a reminder to everyone else as well. You don\'t need a title or a podium to show appreciation. A simple "thank you" in an email or a genuine compliment during a break can change the trajectory of someone’s entire day. Let us build a culture where we are as quick to praise as we are to solve problems. To the team we are honoring today: thank you for your excellence, your integrity, and your heart. We are better because of you, and we are deeply grateful for everything you do.',
  },
  {
    id: 'sys-10',
    type: 'system-prewritten',
    title: 'Farewell Speech',
    content:
      'There is a saying that "every parting is a form of death," but I prefer to think of every goodbye as a necessary birth into a new phase of life. Saying goodbye is never easy, especially when you have built deep roots and shared significant history. We are gathered here to bid farewell to a colleague and a friend who has been an integral part of our story. While there is a natural sadness in seeing a chapter close, there should also be a great deal of pride in the work that was accomplished and the legacy that remains.\n\nTo our departing friend: you aren\'t just leaving a job; you are leaving a mark. The projects you led, the problems you solved, and the people you mentored will continue to thrive long after you have moved on to your next adventure. You have taught us that change is not something to be feared, but something to be embraced as an opportunity for renewal. As you move toward your new horizons, carry with you the knowledge that you have a community here that will always be rooting for your success. \n\nTransitions are the bridges of our lives. They are the spaces where we shed our old selves to make room for who we are becoming. As you step onto this new path, stay true to the values that made you such a valuable part of this team. Be curious, be courageous, and never stop speaking your truth. Though our daily interactions will change, the bond of mutual respect remains. We wish you nothing but the absolute best in all your future endeavors. Thank you for the time, the talent, and the friendship you shared with us. This is not a "goodbye," but a "see you later" on the long road of life.'
  }
];

export const RANDOM_TOPICS = [
  // Original Initial Topics
  { title: 'The Future of Artificial Intelligence', body: 'Share your perspective on how AI will change society in the next decade — the opportunities, the challenges, and what we should do to prepare.' },
  { title: 'A Lesson I Learned the Hard Way', body: 'Tell a personal story about a mistake you made, what it cost you, and the valuable lesson it ultimately taught you.' },
  { title: 'My Favourite Book and Why Everyone Should Read It', body: 'Recommend a book that changed the way you think, feel, or see the world. Explain what made it transformative.' },
  { title: 'The Role of Leadership in Modern Teams', body: 'Discuss what great leadership looks like in today\'s workplace — adapting to remote work, diverse teams, and rapidly shifting priorities.' },
  { title: 'How Social Media is Shaping Society', body: 'Explore both the positive and negative ways social media is influencing how we communicate, form opinions, and understand the world.' },
  { title: 'The Hidden Benefits of Failure', body: 'Argue that failure is one of the most valuable teachers in life. Share examples — personal, historical, or well-known — to support your case.' },
  { title: 'What Makes a City Great to Live In?', body: 'Describe the characteristics that make a city truly liveable — beyond just infrastructure. Consider culture, community, opportunity, and quality of life.' },
  { title: 'The Importance of Sustainable Living', body: 'Make a case for small, everyday changes that can collectively make a big difference for the planet and future generations.' },
  { title: 'Why Financial Literacy Should Be Taught in Schools', body: 'Argue for or against including personal finance as a core subject in school curricula. What are the real-world consequences of financial ignorance?' },
  { title: 'Technology and Human Connection', body: 'Is technology bringing us closer together or pushing us further apart? Defend your position with concrete observations or examples.' },
  { title: 'The Person Who Influenced Me Most', body: 'Speak about someone — a family member, teacher, mentor, or public figure — who shaped who you are today and how they did it.' },
  { title: 'Dreams vs. Practicality: Finding the Balance', body: 'How should a person decide between chasing their passion and making a stable, practical living? Offer your perspective and advice.' },

  // Professional & Tech Topics
  { title: 'Future of Remote Work', body: 'Discuss the long-term impact of digital nomadism on traditional office culture and global talent acquisition.' },
  { title: 'Introverts as Leaders', body: 'Argue why quiet, reflective individuals often make the most exceptional and empathetic leaders.' },
  { title: 'AI and Job Security', body: 'Evaluate the realistic impact of Artificial Intelligence on the labor market. Which sectors are most at risk or most empowered?' },
  { title: 'Building a Personal Brand', body: 'Explain how to differentiate yourself in a crowded digital market without losing authenticity.' },
  { title: 'Diversity in Tech', body: 'Why is diversity and inclusion a requirement for innovation rather than just a HR metric?' },
  { title: 'Corporate Social Responsibility', body: 'Is CSR still optional for large corporations in an era of climate change and social activism?' },
  { title: 'Data Privacy Ethics', body: 'In the age of Big Data, who should be responsible for protecting our digital identities?' },
  { title: 'Crisis Leadership', body: 'How should a leader maintain morale and direction when a team is facing an unprecedented crisis?' },
  { title: 'Emotional Intelligence (EQ)', body: 'Why is EQ often a better predictor of professional success than IQ in modern management?' },
  { title: 'The "Fail Fast" Philosophy', body: 'Explain why rapid experimentation and failure are essential requirements for modern innovation.' },
  { title: 'Four-Day Work Week', body: 'Analyze the productivity and mental health benefits of a shortened work week versus traditional schedules.' },
  { title: 'Blockchain and Finance', body: 'How is decentralized ledger technology transforming the way we think about global currency and trust?' },
  { title: 'Evolution of Marketing', body: 'Trace the shift from broad billboard advertising to the micro-targeted world of social influencers.' },
  { title: 'Lifelong Learning', body: 'Why is the ability to unlearn and relearn the most important career skill of the 21st century?' },
  { title: 'Sustainable Bottom Line', body: 'Argue how environmentally friendly business practices can actually lead to higher long-term profits.' },
  { title: 'The Art of Negotiation', body: 'What are the core strategies for achieving a win-win outcome in high-stakes professional negotiations?' },
  { title: 'The Gig Economy', body: 'Is the rise of freelance labor a sign of freedom or a dangerous erosion of worker protections?' },
  { title: 'The Employee Entrepreneur', body: 'Why should every staff member be encouraged to think like a business owner to drive company growth?' },
  { title: 'Work-Life Balance 24/7', body: 'How do we maintain boundaries in a world where work is always accessible via our smartphones?' },
  { title: 'Consumer Psychology', body: 'What are the subconscious triggers that drive people to choose one brand over another?' },
  { title: 'The Perfect Elevator Pitch', body: 'How do you summarize a complex idea into a compelling 30-second story that wins people over?' },
  { title: 'Corporate Transparency', body: 'Why is radical honesty from leadership essential for building team trust and brand loyalty?' },
  { title: 'Networking as Giving', body: 'Reframing professional networking: Why the best connectors focus on what they can offer, not what they can get.' },
  { title: 'Multi-Generational Workforce', body: 'How can managers bridge the communication gap between Baby Boomers, Gen X, Millennials, and Gen Z?' },
  { title: 'Culture of Creativity', body: 'How do you foster a sense of "safe exploration" in a corporate environment that is traditionally rigid?' },

  // Education & Social Topics
  { title: 'Standardized Testing', body: 'Should standardized tests be abolished in favor of more holistic student assessments?' },
  { title: 'Critical Thinking vs. Fake News', body: 'In an era of deepfakes and misinformation, how do we teach students to verify the truth?' },
  { title: 'College Degree ROI', body: 'Is a traditional four-year university degree still worth the financial investment in 2026?' },
  { title: 'Second Language Education', body: 'Argue for the cognitive and social benefits of mandatory second language learning in early elementary school.' },
  { title: 'Gamification in Classrooms', body: 'How can video game mechanics be used to increase student engagement and knowledge retention?' },
  { title: 'The Importance of STEM', body: 'Why is early exposure to Science, Technology, Engineering, and Math critical for the future economy?' },
  { title: 'The Value of Arts and Music', body: 'Argue why creative subjects are just as vital to human development as the hard sciences.' },
  { title: 'Homeschooling vs. Traditional', body: 'Analyze the social and academic pros and cons of personalized home education versus public schooling.' },
  { title: 'The Student Loan Crisis', body: 'Propose a solution to the mounting debt crisis facing graduates around the world today.' },
  { title: 'Social Media Attention Spans', body: 'How is short-form content (TikTok/Reels) affecting the cognitive ability of students to focus on long tasks?' },
  { title: 'Mandatory Mental Health Ed', body: 'Should schools be required to teach emotional regulation and mental health as a core subject?' },
  { title: 'CRISPR and Genetic Ethics', body: 'As we gain the power to "edit" humans, where should the global community draw the ethical line?' },
  { title: 'Preparing for Non-Existent Jobs', body: 'How do you design a curriculum for career paths that haven\'t even been invented yet?' },
  { title: 'Financial Literacy for Graduates', body: 'Why should every high school student master budgeting, taxes, and investing before they graduate?' },
  { title: 'Physical Ed and Academics', body: 'Discuss the scientific link between regular physical movement and improved cognitive performance.' },
  { title: 'The Future of Space Exploration', body: 'Should we prioritize colonizing Mars or solving the environmental crises on our home planet first?' },
  { title: 'Year-Round Schooling', body: 'Analyze the benefits of a year-round academic calendar versus the traditional long summer break.' },
  { title: 'The Digital Divide', body: 'How can we ensure that students in developing nations aren\'t left behind as education moves online?' },
  { title: 'The Gap Year Benefit', body: 'Why should students be encouraged to take a year off between high school and college to gain real-world perspective?' },
  { title: 'Philosophy in Modern Science', body: 'Does scientific research need a foundation in philosophy to ensure it serves the common good?' },
  { title: 'Teenage Peer Pressure', body: 'How can educators help teenagers build the confidence to resist negative social influences?' },
  { title: 'Protecting Endangered Languages', body: 'Why is preserving linguistic diversity essential for maintaining global cultural heritage?' },
  { title: 'Voting Age at 16', body: 'Argue for or against lowering the legal voting age to give the youth a greater say in their future.' },
  { title: 'The Science of Sleep', body: 'How does chronic sleep deprivation among students affect national education outcomes?' },
  { title: 'Women in Engineering', body: 'What practical steps can be taken to encourage more women to pursue careers in historically male-dominated STEM fields?' },

  // Personal Growth & Mindset
  { title: 'Failure as a Teacher', body: 'Discuss why your most embarrassing mistakes are often your most powerful educational moments.' },
  { title: 'The Power of Mindset', body: 'How can a "Growth Mindset" fundamentally change the way you perceive obstacles and personal limits?' },
  { title: 'The Highlight Reel Trap', body: 'Why we should stop comparing our internal struggles to the curated "perfect" lives of others on social media.' },
  { title: 'Visualizing Success', body: 'Is there a scientific basis for goal-setting and visualization, or is it just positive thinking?' },
  { title: 'Acts of Kindness', body: 'How can a single, small gesture of goodwill create a ripple effect that transforms a whole community?' },
  { title: 'Vulnerability as Strength', body: 'Following the research of Brené Brown, why is the courage to be vulnerable the key to true leadership?' },
  { title: 'The Power of Persistence', body: 'Tell a story (real or hypothetical) about why not giving up is the most important factor in achieving a dream.' },
  { title: 'Finding Your "Why"', body: 'How does discovering your core purpose change the way you approach mundane or difficult tasks?' },
  { title: 'Gratitude and Happiness', body: 'Discuss the psychological impact of daily gratitude practice on overall life satisfaction.' },
  { title: 'Embracing Discomfort', body: 'Why staying inside your comfort zone is actually the most dangerous place for your personal growth.' },
  { title: 'Building Resilience', body: 'What are the specific mental strategies needed to bounce back after a significant life or career setback?' },
  { title: 'Embracing Your Unique Self', body: 'In a world of "standardized" beauty and success, why is your weirdness actually your greatest asset?' },
  { title: 'Time as a Resource', body: 'If time is our only non-renewable resource, why do we spend it so carelessly? Discuss intentional living.' },
  { title: 'The Impact of Mentorship', body: 'How does having a mentor accelerate your learning curve and prevent you from making common mistakes?' },
  { title: 'The Inner Critic', body: 'How do you differentiate between helpful self-correction and the destructive "inner critic" that holds you back?' },
  { title: 'Journey vs Destination', body: 'Why do we often find that the process of achieving a goal is more rewarding than the goal itself?' },
  { title: 'Self-Care and Well-being', body: 'Why is self-care a requirement for high performance, not a luxury or a sign of laziness?' },
  { title: 'Passion to Career', body: 'What are the practical steps to turning a hobby you love into a sustainable and profitable career?' },
  { title: 'Starting New at Any Age', body: 'Debunk the myth that you are "too old" to learn a new skill or change your life direction.' },
  { title: 'Storytelling for Change', body: 'How can a well-told story move people to action more effectively than a list of statistics?' },
  { title: 'Honesty in Relationships', body: 'Why is radical honesty, even when it\'s painful, the only way to build a relationship that lasts?' },
  { title: 'Leading with Empathy', body: 'Is it possible to be both a "strong" leader and a compassionate, empathetic one?' },
  { title: 'Forgiveness and Peace', body: 'Why is forgiving others (and yourself) essential for your own mental and physical health?' },
  { title: 'Courage vs Fear', body: 'Redefining courage: It\'s not about being fearless, but about doing what needs to be done while you are afraid.' },
  { title: 'Purposeful Living', body: 'What does it look like to live a life with intention rather than just reacting to external events?' },

  // Lifestyle, Culture & Fun
  { title: 'Cats Ruling the World', body: 'A fun exploration of why humans are so obsessed with cats and how they managed to "conquer" the internet.' },
  { title: 'Meme Communication', body: 'Are memes the new universal language? Discuss their role in modern political and social discourse.' },
  { title: 'Pineapple on Pizza', body: 'The ultimate culinary debate. Defend your position with passion—is it a masterpiece or a crime?' },
  { title: 'Fast Fashion Impact', body: 'Discuss the environmental and ethical cost of $5 t-shirts and the rise of "throwaway" culture.' },
  { title: 'True Crime Obsession', body: 'Why is the human brain so attracted to dark, suspenseful, and often terrifying real-life stories?' },
  { title: 'Digital Detox Benefits', body: 'What happens to our brains and stress levels when we unplug from technology for a full weekend?' },
  { title: 'Signature Dish Cooking', body: 'Why should every adult master at least one impressive meal they can cook for others?' },
  { title: 'Superhero Culture', body: 'How have Marvel and DC shaped the modern "mythology" and what we consider to be heroic?' },
  { title: 'Time in Nature', body: 'Explore the "Biophilia" hypothesis: Why being near trees and water is essential for human mental health.' },
  { title: 'The Smart Home Future', body: 'Are we becoming too reliant on "Alexa" and "Siri"? Discuss the trade-off between ease and privacy.' },
  { title: 'Essential Hobbies', body: 'Why having a productive hobby outside of work is the key to preventing burnout.' },
  { title: 'Urban Gardening', body: 'How can growing food in cities help solve food insecurity and improve the "concrete jungle" environment?' },
  { title: 'Influencer Ethics', body: 'Should people with millions of followers be held to the same truth-seeking standards as traditional journalists?' },
  { title: 'Cancel Culture Double-Edge', body: 'Analyze how social media call-outs can both protect the vulnerable and destroy lives without due process.' },
  { title: 'Transportation Future', body: 'Hyperloops, flying taxis, and self-driving pods—which will actually become a reality first?' },
  { title: 'Single-Use Plastics', body: 'What are the most innovative ways we can move toward a truly plastic-free global economy?' },
  { title: 'Local over Global', body: 'Why is supporting your neighborhood "mom and pop" shop more important for the economy than buying from giants?' },
  { title: 'Internet: Connection or Isolation?', body: 'Does the internet make us feel like we belong, or does it highlight how alone we really are?' },
  { title: 'The Pet Psychology', body: 'How does owning a dog or cat physiologically lower cortisol and improve heart health in humans?' },
  { title: 'Cultural Travel Education', body: 'Why is experiencing a completely different culture more educational than reading any history book?' },
  { title: 'Sports and National Identity', body: 'How do events like the World Cup or Olympics bring nations together (or drive them apart)?' },
  { title: 'Zombie Apocalypse Survival', body: 'A fun hypothetical: What would be your three-step plan to survive the first week of a zombie outbreak?' },
  { title: 'Minimalist Living', body: 'Why is the "Less is More" philosophy gaining so much traction in a world of hyper-consumerism?' },
  { title: 'Reality TV Perception', body: 'How has the "scripted reality" of TV shows changed our expectations for how our own lives should look?' },
  { title: 'Laughter as Medicine', body: 'Discuss the biological benefits of laughter on the immune system and pain management.' },
  { title: 'Deepfake Ethics', body: 'What are the dangers of a world where we can no longer trust our eyes and ears in digital media?' },
  { title: 'Solo Travel Benefits', body: 'Why every person should go on a trip entirely by themselves at least once in their lifetime.' },
  { title: 'The Butterfly Effect', body: 'How a tiny, seemingly insignificant choice you made years ago completely changed your life today.' },
  { title: 'The Future of Meat', body: 'Is lab-grown beef a viable solution to the environmental impact of traditional cattle farming?' },
  { title: 'Physical Books vs E-readers', body: 'Argue for the tactile, sensory experience of real paper over the convenience of a digital screen.' },
  { title: 'Preserving Oral Tradition', body: 'In a digital world, why is the ancient art of spoken storytelling still vital for cultural survival?' },
  { title: 'Music and Productivity', body: 'How does different "BPM" (beats per minute) in music affect the way we work and think?' },
  { title: 'Ocean vs Space Exploration', body: 'Should we spend our resources exploring the 95% of the ocean that remains a mystery before we go to Mars?' },
  { title: 'Interior Design Psychology', body: 'How the color of the walls and the layout of a room can fundamentally change your mood.' },
  { title: 'The Art of Listening', body: 'In a world that won\'t stop talking, how do you become the person who actually hears?' },
  { title: 'E-sports as Real Sports', body: 'Should professional gaming be included in the Olympics? Defend your position.' },
  { title: 'Handwriting Relevancy', body: 'Is penmanship still a necessary skill in an age where everyone communicates via keyboard?' },
  { title: 'Light Pollution Impact', body: 'How the lack of a "dark sky" is affecting our sleep patterns and the behavior of nocturnal wildlife.' },
  { title: 'Spotting Logical Fallacies', body: 'How to recognize when someone is using a "Straw Man" or "Ad Hominem" attack in a debate.' },
  { title: 'Secret Societies History', body: 'From the Illuminati to the Freemasons—why are humans so fascinated by hidden organizations?' },
  { title: 'Boredom is Good', body: 'Why constant stimulation is killing our creativity and why we should let ourselves be bored more often.' },
  { title: 'Renewable Energy Future', body: 'Look beyond solar and wind: Could tidal power or geothermal energy be the real key to a green future?' },
  { title: 'Colonizing Mars', body: 'Discuss the immense logistical and biological challenges of building the first human city on a dead planet.' },
  { title: 'Universal Basic Income', body: 'As robots take our jobs, is a government salary for everyone the only way to prevent social collapse?' },
  { title: 'Classical Music in 2026', body: 'Why the works of Mozart and Beethoven still resonate in a world of 15-second TikTok sounds.' },
  { title: '3D Printing in Medicine', body: 'How the ability to "print" organs and custom prosthetics is revolutionizing modern healthcare.' },
  { title: 'Internet of Things (IoT)', body: 'Is having a "smart" toaster worth the risk of your entire home network being hacked?' },
  { title: 'The Procrastination Cycle', body: 'Why do we wait until the last minute even when we know it will cause us immense stress?' },
  { title: 'Philosophy for Kids', body: 'Should children be taught how to question the nature of reality and morality from a young age?' },
  { title: 'Mythology in Cinema', body: 'How modern blockbusters like Star Wars or Lord of the Rings are just retellings of ancient myths.' },
  { title: 'Low-Cost Sustainability', body: 'What are the ways to be eco-friendly without having to buy expensive "green" products?' },
  { title: 'Zoo Ethics', body: 'Are zoos essential for conservation and education, or are they outdated institutions of animal cruelty?' },
  { title: 'Discipline vs Talent', body: 'Why the "hard worker" almost always beats the "talented natural" in the long run.' },
  { title: 'Human-Robot Relationships', body: 'As AI gets more realistic, will we eventually treat robots as friends, or even family members?' },
  { title: 'First 100 Days of a Job', body: 'How do you navigate the social and professional landmines of a brand new workplace environment?' },
  { title: 'Fragile Ecosystem Tourism', body: 'Should we ban tourism to places like the Galapagos or Antarctica to save them from human impact?' },
  { title: 'Public Parks for Cities', body: 'Why green spaces are a requirement for urban mental health, not just a "nice-to-have" luxury.' },
  { title: 'Digital Legacy after Death', body: 'What happens to our social media and private data when we pass away? Who should own it?' },
  { title: 'Dialogue in Polarized Society', body: 'How can we have a respectful conversation with someone who holds the complete opposite political view?' },
  { title: 'Propaganda Awareness', body: 'How can we spot the subtle ways that media and governments try to manipulate our opinions today?' },
  { title: 'Reinventing Education', body: 'If you could start a school from scratch, what would be the three most important things you would teach?' },
  { title: 'Plant-Based Planet', body: 'What would the world actually look like if everyone became a vegetarian for just one month?' },
  { title: 'Virtual Reality Travel', body: 'Will we ever stop traveling in the real world if VR can perfectly simulate the Taj Mahal or the Great Wall?' },
  { title: 'AI as Artists', body: 'Can a machine truly be creative, or is AI-generated poetry just a sophisticated form of plagiarism?' },
  { title: 'The Golden Rule', body: 'Is "Treat others as you want to be treated" really enough to solve the world\'s complex moral problems?' },
  { title: 'Long-Distance Friendship', body: 'What are the specific habits that keep a friendship alive when you live thousands of miles apart?' },
  { title: 'Noise Pollution Impact', body: 'How the constant roar of city traffic and sirens is changing the song patterns of urban birds.' },
  { title: 'Critical Thinking: Future Skill', body: 'Why the ability to analyze information is more important than the ability to memorize it in the age of Google.' },
  { title: 'Fashion as Politics', body: 'How have different styles of clothing been used throughout history to signal rebellion or social change?' },
  { title: 'Information Overload Management', body: 'How do you stay informed about the world without being overwhelmed by the constant stream of news?' },
  { title: 'Indigenous Knowledge', body: 'Why should modern scientists listen to the traditional wisdom of native tribes when it comes to conservation?' },
  { title: 'Screen Time for Adults', body: 'Is adult smartphone addiction just as dangerous for society as child screen time?' },
  { title: 'Community Gardens Resilience', body: 'How neighborhood gardens can help a community survive a natural disaster or an economic crash.' },
  { title: 'Staying Hopeful in 2026', body: 'In a world of constant bad news, how do you find the motivation to keep working toward a better future?' },
  { title: 'Habit Formation Science', body: 'Explain the "Trigger, Routine, Reward" loop and how to use it to break a bad habit forever.' },
  { title: 'Female Rep in Government', body: 'How would global policies on climate and health change if 50% of world leaders were women?' },
  { title: 'Micro-transactions in Gaming', body: 'Are "loot boxes" and "battle passes" a fair way to fund games, or are they just predatory gambling?' },
  { title: 'Art of Public Debate', body: 'How to defend your position with facts and logic without losing your temper or insulting your opponent.' },
  { title: 'Morning Routine Clarity', body: 'How the first 60 minutes of your day determines the productivity of your entire afternoon.' },
  { title: 'Rethinking Retirement', body: 'Is the traditional concept of "working until 65 and then stopping" still relevant for the modern workforce?' },
  { title: 'Satire and Power', body: 'Why comedians and satirists are often the most important truth-tellers in a functioning democracy.' },
  { title: 'Mental Health in Election Years', body: 'How to stay politically engaged without letting the stress of an election destroy your inner peace.' },
  { title: 'Space Tourism Ethics', body: 'Should the ultra-wealthy be allowed to burn tons of rocket fuel just for a few minutes of zero-gravity?' },
  { title: 'Public Transport over Cars', body: 'Make a case for why the future of a great city depends on trains and buses rather than private vehicles.' },
  { title: 'Hustle Culture Burnout', body: 'Is the "Rise and Grind" mentality actually productive, or is it just a recipe for chronic exhaustion?' },
  { title: 'Community in a Big City', body: 'How to overcome "Urban Loneliness" and find a group of people you truly belong with in a metropolis.' },
  { title: 'Teaching Children to Fail', body: 'Why protecting children from every small failure is actually making them less prepared for adulthood.' },
  { title: 'Curiosity as a Trait', body: 'Why the simple act of asking "Why?" is the most powerful tool for both personal and professional growth.' },
  { title: 'Wearable Tech Future', body: 'Will our watches eventually know more about our health than our doctors do? Discuss the implications.' },
  { title: 'Echo Chamber Effect', body: 'How to recognize when your social media feed is only showing you things that you already agree with.' },
  { title: 'Local Libraries in Digital Age', body: 'Why libraries are becoming even more important as safe, free spaces for community connection and learning.' },
  { title: 'First Aid and CPR', body: 'Argue why every citizen should be required to take a basic life-saving course to graduate from high school.' },
  { title: 'Fast Furniture Waste', body: 'Discuss the environmental cost of "disposable" desks and chairs that end up in landfills every few years.' },
  { title: 'Productive Disagreement', body: 'How to have a conversation where you learn something from someone who has the complete opposite worldview.' },
  { title: 'Nostalgia Psychology', body: 'Why does our brain filter out the bad parts of the past and make us long for "the good old days"?' },
  { title: 'Invest in Libraries', body: 'Why libraries are the most efficient use of tax dollars for improving community literacy and happiness.' },
  { title: 'Ethical Hacking Importance', body: 'How "White Hat" hackers are the unsung heroes of the modern world, protecting our banks and hospitals.' },
  { title: 'Conscious Consumption', body: 'How your spending habits can be a form of "voting" for the kind of world you want to live in.' },
  { title: 'Personalized DNA Medicine', body: 'How genetic testing will eventually allow doctors to prescribe the perfect medicine for your specific body.' },
  { title: 'Protecting National Parks', body: 'Why we must keep these wild spaces free from commercial development, no matter how much money is offered.' },
  { title: 'Influencers and Self-Esteem', body: 'How the "perfect" bodies we see on Instagram are creating a global crisis of body dysmorphia.' },
  { title: 'Sustainable Wardrobe on Budget', body: 'Tips and tricks for building a high-quality, eco-friendly closet without being a millionaire.' },
  { title: 'Volunteering Development', body: 'Why giving your time for free is actually one of the fastest ways to build new professional skills.' },
  { title: 'Soft Skills vs Hard Skills', body: 'Why empathy and communication will always be more valuable than technical skills that can be automated.' },
  { title: '15-Minute Neighborhoods', body: 'The urban planning dream: Being able to reach everything you need within a 15-minute walk from home.' },
  { title: 'Reading for Pleasure', body: 'How to break the "Doom-scrolling" habit and rediscover the immersive joy of getting lost in a novel.' },
  { title: 'Global Cultural Exchange', body: 'How interacting with people from different countries prevents the growth of prejudice and xenophobia.' },
  { title: 'Phone vs In-Person', body: 'Why a 10-minute face-to-face conversation is more meaningful than a week of texting.' },
  { title: 'Poetry and Human Condition', body: 'Why we still turn to poems during weddings, funerals, and heartbreaks when normal words aren\'t enough.' },
  { title: 'Mindfulness in Busyness', body: 'How to find "the eye of the storm" and stay calm even when your environment is chaotic.' },
  { title: 'Light and Circadian Rhythm', body: 'How the "Blue Light" from our devices is tricking our brains into thinking it\'s always daytime.' },
  { title: 'Trade School Value', body: 'Why society needs to stop looking down on vocational training and recognize the high value of skilled trades.' },
  { title: 'Work From Home Future', body: 'Will the traditional 9-to-5 in a cubicle eventually become a historical curiosity?' },
  { title: 'Creativity when Uninspired', body: 'What are the specific "creative warm-ups" you can use to get the ideas flowing when your brain feels empty?' },
  { title: 'Knowing Local History', body: 'Why understanding the history of your specific town or city makes you a more engaged and active citizen.' },
  { title: 'Internet as Utility', body: 'Should high-speed internet be treated as a basic human right, like water and electricity?' },
  { title: 'Fast-Paced Lifestyle Health', body: 'How our modern "Go-Go-Go" culture is leading to a global epidemic of heart disease and anxiety.' },
  { title: 'Thicker Skin to Criticism', body: 'How to separate your "Self-Worth" from the opinions of others, especially anonymous ones online.' },
  { title: 'Trust in Democracy', body: 'Why a democratic society cannot function if citizens lose faith in their institutions and each other.' },
  { title: 'Scientific Literacy Importance', body: 'Why every citizen needs to understand the "Scientific Method" to make informed decisions about their health.' },
  { title: 'Is the Cinema Dying?', body: 'With streaming services becoming so powerful, will we still be going to movie theaters in 2030?' },
  { title: 'Aligning with Core Values', body: 'How to perform a "Life Audit" to see if your daily actions actually match what you say is important to you.' },
  { title: 'Ritual and Tradition', body: 'In a fast-changing world, why do we still need the comfort of repeated rituals and seasonal traditions?' },
  { title: 'Standing Against Cyberbullying', body: 'What can an individual do to make the digital world a safer and kinder place for everyone?' },
  { title: 'Attention Economy Focus', body: 'How to reclaim your focus from apps that are specifically designed to be as addictive as possible.' },
  { title: 'Meaning in Everyday Tasks', body: 'How the philosophy of "Zen" can help you find fulfillment in washing dishes or commuting to work.' },
  { title: 'Humor as a Coping Mechanism', body: 'Why being able to find something funny in a dark situation is a sign of high mental resilience.' },
  { title: 'Celebrating Mistakes', body: 'How a culture that "cheers" for typos and errors can actually lead to much faster innovation.' },

  // Filipino Context & 2026 Trends
  { title: 'The Resilience of the Filipino Spirit', body: 'Discuss the unique concept of "Bayanihan" and how it helps the Philippines overcome national challenges.' },
  { title: 'Preserving Local Dialects', body: 'Beyond Tagalog, why is it vital to protect the 180+ languages across the Philippine archipelago?' },
  { title: 'The Rise of the "P-Pop" Wave', body: 'How Filipino music is starting to carve its own unique space on the global stage alongside K-Pop.' },
  { title: 'Modernizing the Jeepney', body: 'Discuss the cultural and environmental trade-off in the plan to modernize the most iconic Filipino transport.' },
  { title: 'Adopting Digital Payments in PH', body: 'How GCash and Maya have changed the way Filipinos manage money—and the challenges of the "unbanked".' },
  { title: 'Social Media Capital of the World', body: 'Why are Filipinos consistently the most active people on social media globally? Discuss the pros and cons.' },
  { title: 'The "Brain Drain" Challenge', body: 'How can the Philippines encourage its highly skilled professionals to build their careers at home?' },
  { title: 'Eco-Tourism in Paradise', body: 'How can local communities balance the need for tourism income with the protection of spots like Siargao and El Nido?' },
  { title: 'The Value of "Filipino Time"', body: 'Is the concept of "Filipino Time" a harmless cultural quirk or a barrier to national productivity?' },
  { title: 'Street Food as Cultural Heritage', body: 'Why the local "Ihaw-ihaw" and "Balut" are more than just snacks—they are part of the Filipino identity.' }
];